import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from .dataprocess import clean, load
from pathlib import Path
import mlflow
import argparse

def train(data_path,seed):
    df = load(data_path)
    df = clean(df)

    d = df.dropna(subset=['CO(GT)', 'PT08.S1(CO)'])

    X = d[['PT08.S1(CO)']]
    y = d['CO(GT)']

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=seed)

    model = LinearRegression().fit(X_train, y_train)
    score = r2_score(y_test, model.predict(X_test))

    return model, score

# Argument Part is generated by ChatGPT
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument(
        "--data-path",
        default="data/AirQualityUCI.csv",
    )
    args = parser.parse_args()

    model, score = train(args.data_path, args.seed)

    mlflow.set_tracking_uri("sqlite:///mlflow.db")
    mlflow.set_experiment("sensorlab")

    with mlflow.start_run(run_name=f"seed-{args.seed}"):
        mlflow.log_params({"seed": args.seed,"data": Path(args.data_path).name})
        mlflow.log_metric("r2", score)

    print(f"r2={score}")
    print(f"slope {model.coef_[0]:.5f}, "f"intercept {model.intercept_:.5f}")
    

if __name__ == '__main__':
    main()
